# Basic Information 
title: xiaojx()
position: CS Master Student
affiliation: ShanghaiTech University
email: xiaojx2025@shanghaitech.edu.cn

# SEO settings
url: "https://xiaojxkevin.github.io"
baseurl: ""

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Jinxi Xiao, ShanghaiTech University, Computer Science, Embodied AI, 3D Vision
description: Personal academic homepage of Jinxi Xiao, a graduate student at ShanghaiTech University researching Embodied AI and 3D Vision.
# canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
#google_scholar: https://scholar.google.com/
#cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/xiaojxkevin
zhihu_link: https://www.zhihu.com/people/xiaojx005
#linkedin: https://www.linkedin.com/
#twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: 

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

permalink: /blog/:year/:month/:day/:title/

collections:
  projects:
    output: true
    permalink: /projects/:title/

plugins:
  - jekyll-remote-theme
  - jekyll-scholar

scholar:
  style: ieee
  locale: en
  source: ./_bibliography
  bibliography: references.bib
  bibliography_list_tag: ol
  bibliography_item_tag: li
  bibliography_class: bibliography
  replace_strings: true
  join_strings:  true
  details_dir: bibliography
  details_link: Details
  query: "@*"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
  - Dockerfile
  - docker-compose.yml
  - private
