services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729" # LiveReload
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --livereload --force_polling
